version: '3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${DB_USER} -d $${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env
    networks:
      - authnetwork

  service:
    build: .
    image: app_django
    restart: always
    volumes:
      - ./movies_app/static:/opt/app/movies_app/static/
      - ./movies_app/media:/opt/app/movies_app/media/
    ports:
      # тесты Postman Yandex Practicum смотрят на 8000 порт, поэтому убрать его не могу
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    networks:
      - authnetwork

  nginx:
    image: nginx:1.25.4
    restart: always
    volumes:
      - ./movies_app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_app/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./movies_app/static:/app/static/
      - ./movies_app/media:/app/media/
    depends_on:
      - service
    ports:
      - "80:80"
    networks:
      - authnetwork

  auth-service:
    build: ../auth_service/
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      cache:
        condition: service_started
    env_file: .env
    networks:
      - authnetwork

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - authnetwork
    ports:
      - "127.0.0.1:9200:9200"

  etl:
    build: etl/
    image: etl_service
    env_file:
      - .env
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - authnetwork

  cache:
    image: redis:7.2.4-alpine
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
     - ./redis-data:/var/lib/redis
    networks:
      - authnetwork

networks:
  authnetwork: